### ISSUE TITLE
Semi-colon as first character causes corruption

### ISSUE THREAD

**Issue by jfichtner** [j123b567/scpi-parser#103]
When a semicolon character is the first character in the data string passed into SCPI_Input, the parser enters a state where it can no longer function properly. In attempting to characterize this issue, I found that the [while(1) loop in SCPI_Input breaks](https://github.com/j123b567/scpi-parser/blob/007889b4128e8656c55ba31404a698e98719c262/libscpi/src/parser.c#L343) when the termination detected by scpiParser_detectProgramMessageUnit is not newline, and the programHeader.type == SCPI_TOKEN_UNKNOWN, which is the case when a semicolon is the first character. Then every subsequent call to SCPI_Input continues to start parsing at the semicolon, and bails out immediately. Therefore no further commands will ever be interpreted.

I understand that the semicolon as the first character is not a valid case, but I assume you would agree that it shouldn't cause the library to essentially hang (from a user's perspective)? I would think that we would want to push an error and reset the buffer, as is done in the case where the input buffer is overrun. Thoughts?

**Comment by j123b567** [comment]
Thanks for reporting. It should be fixed now.
