### ISSUE TITLE
Example of Optional keywords/Related API

### ISSUE THREAD

**Issue by kbastronomics** [j123b567/scpi-parser#125]
On the API documentation you have MEASure:VOLTage[:DC]? but no related API.
Which API would be used to get the Optional keyword(s) 
Can the Documentation be updated for this please?

Sandra

**Comment by j123b567** [comment]
There is no API exposed to the user to work with command patterns. Just specify the list of patterns and commands and pass it to the `SCPI_Init` which is already stated in https://j123b567.github.io/scpi-parser/basic/instrument/

Then every time the user writes command, correct command handler is called for you. So if you specify the pattern `"MEASure:VOLTage[:DC]?"`, these commands will match and call your callback:

```
MEAS:VOLT?
MEAS:VOLT:DC?
measure:volt?
:meas:volt:dc?
...
```

In the callback, it is undistinguishable, which command the user really used. If you need to distinguish some commands, you should specify separate patterns and callbacks for them (or same callback but different `tag`).

You can use more complex patters like `OUTPut#[:MODulation#]:FM`.

Just for completeness, there is a [unit test](https://github.com/j123b567/scpi-parser/blob/master/libscpi/test/test_scpi_utils.c#L550) for the pattern matching and there is lot of patterns and commands and result, if they match or not.
