### ISSUE TITLE
how to handle odd units

### ISSUE THREAD

**Issue by karlp** [j123b567/scpi-parser#14]
I know that I can provide my own entire array of units, but do you have ideas on how best to handle things like "Vrms" and Vpp, while _still_ keeping all the existing SI unit prefixes?  so I can have mVrms and uVrms without having to to duplicate all the units for all the combinations?

I'm probably just going to ignore supporting this in the direct SOURce#:APPLy:SIN [freq], [ampl], [offset] type functions, and only allow changing it via the explicit SOURce#:VOLTage:UNIT command, but was wondering if you had any ideas on how best to handle this

**Comment by j123b567** [comment]
Just make two separate issues from this #26 and #25 so closing this.
