### ISSUE TITLE
How the MAV bit is setting in Status register.

### ISSUE THREAD

**Issue by abhimanyukk-druck-utthunga** [j123b567/scpi-parser#151]

**Comment by jancumps** [comment]
It's set in [Flush](https://github.com/j123b567/scpi-parser/blob/4e879901b51cbb43dab36dd83f95a23f1dbaa4c0/examples/test-vxi11/main.c#L72)

Checked when [writing the reply ](https://github.com/j123b567/scpi-parser/blob/4e879901b51cbb43dab36dd83f95a23f1dbaa4c0/examples/test-vxi11/main.c#L51)
