### ISSUE TITLE
Does this project support mutithread application?

### ISSUE THREAD

**Issue by YongningW** [j123b567/scpi-parser#160]
well, i would like to use this scpi-parser in a mutithread application, is there any guides? thanks.

**Comment by j123b567** [comment]
Library is not thread safe. See #69

**Comment by YongningW** [comment]
I have another question, how to improve the parsing time of commands on embedded devices (such as STM32 devices). I tested that it takes about 1ms to parse a double type of data, any suggestions for improvement, thank you very much

**Comment by YongningW** [comment]
@j123b567
