### ISSUE TITLE
New entry in scpi_special_number_t suggested

### ISSUE THREAD

**Issue by andrey-nakin** [j123b567/scpi-parser#20]
CONFigure command accept following values for the 1st arguments: DEF, MIN, MAX, AUTO, <explicit number>. Examples:

CONF:VOLT:DC DEF
CONF:VOLT:DC 12.34
CONF:VOLT:DC AUTO

I'd like to use SCPI_ParamNumber to parse command, but scpi_special_number_t enumeration has no option for AUTO value. Can you add it? Or can I add an exception for this command only to support AUTO option?

Thanks

**Comment by j123b567** [comment]
I have implemented better handling of this in experimental branch. You are not forced to use default list of special values but you can define it per parameter.

In the first step, there is nothing against adding AUTO as additional special value.

In the second step, I will try to backport this feature from experimental branch to old version.

**Comment by andrey-nakin** [comment]
Thanks for reply. I'll look forward to the next release.

**Comment by andrey-nakin** [comment]
Thank you!
