### ISSUE TITLE
IEEE 488.2-2004:8.4.1 <RESPONSE MESSAGE UNIT SEPARATOR>

### ISSUE THREAD

**Issue by andrey-nakin** [j123b567/scpi-parser#21]
When I send two or more query commands in a single packet like this:

*OPC?;SYST:ERR?

my Agilent 34401A returns all responses in the single line separated by semicolon:

1;0, "No error"

It is possible to implement this in scpi-parser? Currently command responses are separated by a new line.

**Comment by j123b567** [comment]
I will look at this. It will be nice feature.
Nevertheless, I think that standard forbids this at all but I must investigate it little bit.

**Comment by j123b567** [comment]
According to the standard, it is possible to call multiple Queries at once.

Multiple responses from one command should be separated by "," which is already done.

Multiple responses should be separated by <RESPONSE MESSAGE UNIT SEPARATOR> - ";" - this will be implemented.

**Comment by andrey-nakin** [comment]
Great fix, thank you!
