### ISSUE TITLE
Unexpected error -108

### ISSUE THREAD

**Issue by andrey-nakin** [j123b567/scpi-parser#29]
I added a handler for command SENSE:FUNCTION that accepts a single argument in double quotes:

SENSE:FUNCTION "VOLT"

My handler looks like this:

~~~~~~~
scpi_result_t sense_function(scpi_t* context) {
    const char* param;
    size_t param_len;

    if (!SCPI_ParamText(context, &param, &param_len, TRUE)) {
        return SCPI_RES_ERR;
    }

    // process param

    return SCPI_RES_OK;
}
~~~~~~~

It works well and returns SCPI_RES_OK, but after it returns the SCPI parser pushes error -108 to error stack.

**Comment by j123b567** [comment]
Thank you for reporting this. Can you try this fix?

**Comment by andrey-nakin** [comment]
It works now, thanks
