### ISSUE TITLE
SCPI-99:8.3.2 Channel Lists

### ISSUE THREAD

**Issue by ChristianBaumgarten** [j123b567/scpi-parser#3]
Thank you for sharing a great SCPI library.
Is it correctly understood that the library does not support source lists? Do you have any plans about adding support for it?
Best Regards
Christian

**Comment by koeart** [comment]
Hey,

I wanted to ask if this issue is still open or if the code was already enhanced?

@j123b567 Thanks for the amazing work so far!

**Comment by j123b567** [comment]
This is still missing feature. I have some plans how to do it, but not much time.

It is easy to implement it using `SCPI_Parameter()`, check type of the parameter - should be `SCPI_TOKEN_PROGRAM_EXPRESSION` and parse the string `(@....)` - range by range.

If you would like to share some code, I can incorporate it in the library.
