### ISSUE TITLE
scpi_interface_t.error is not called

### ISSUE THREAD

**Issue by andrey-nakin** [j123b567/scpi-parser#33]
I specified my own handler to `scpi_interface_t.error`, but it is not called when an error occurs. Is this handler overridden somewhere?

**Comment by j123b567** [comment]
It should work. I have a test case for it and it pass all tests. Can you show me example command handler and example command that should generate an error?

**Comment by andrey-nakin** [comment]
Excuse, that was my fault.

**Comment by j123b567** [comment]
ok
