### ISSUE TITLE
get unsigned integers with SCPI_ParamNumber

### ISSUE THREAD

**Issue by bitwigglers** [j123b567/scpi-parser#39]
Is it  possible with the current API to retrieve an unsigned integer value from a numeric parameter like "#hffffffff"?

**Comment by bitwigglers** [comment]
SCPI_ParamDouble can be used, since a double can represent all 32 bit integers.

**Comment by j123b567** [comment]
This will not solve your problem. I should extend the API to support this.

**Comment by j123b567** [comment]
If the number is HEX, BIN or OCT, it is always converted by `SCPI_ParamToInt` - with sign and then converted to double in `SCPI_ParamDouble` - still preserve the sign and still wrong number.

**Comment by bitwigglers** [comment]
You are right. I just saw that SCPI_ParamToDouble() calls SCPI_ParamToInt() for non-decimal numbers.

**Comment by j123b567** [comment]
You can now use `SCPI_ParamUnsignedInt`, `SCPI_ParamDouble` or `SCPI_ParamNumber`. All should work as expected.

**Comment by bitwigglers** [comment]
Wow, that was a quick fix. Will test it asap. Thank you very much!
