### ISSUE TITLE
SCPI_CommandNumbers

### ISSUE THREAD

**Issue by mvladic** [j123b567/scpi-parser#54]
Using `SCPI_CommandNumbers()` function it is not possible to find out if number is typed or not because in case if number is not typed it will just return 1. I have a use case when I need to know when number is not typed. Is there a way to find out if number is typed?

**Comment by j123b567** [comment]
It is currently not possible.
I can introduce additional parameter, where you can specify default value and later test if value is default or not. Will this be helpfull for you?

**Comment by mvladic** [comment]
That would be great, thanks!
