### ISSUE TITLE
Unexpected parser behaviour

### ISSUE THREAD

**Issue by mvladic** [j123b567/scpi-parser#56]
I have defined following SCPI commands:

    ...
    { .pattern = "MEASure[:SCALar]:CURRent[:DC]?", .callback = SCPI_MeasureCurrentQ, },
    { .pattern = "MEASure[:SCALar]:POWer[:DC]?",   .callback = SCPI_MeasurePowerQ,   },
    { .pattern = "MEASure[:SCALar]:VOLTage[:DC]?", .callback = SCPI_MeasureVoltageQ, },
    ...

But parser is also accepting :MEAS? as regular header and calls SCPI_MeasureCurrentQ callback. Is this ok?

**Comment by j123b567** [comment]
No, it is not ok.
