### ISSUE TITLE
Question: SCPI_ERROR_INVALID_STRING_DATA

### ISSUE THREAD

**Issue by mvladic** [j123b567/scpi-parser#72]
When is `SCPI_ERROR_INVALID_STRING_DATA` error is generated?

**Comment by j123b567** [comment]
If you write parameter, that is not supported parameter type.

According to this https://coveralls.io/builds/4364348/source?filename=libscpi%2Fsrc%2Fparser.c#L636 there is already test, that cause this error, but I don't know which test. I would like to write explicit one.

**Comment by j123b567** [comment]
There is at least one test in `test_parser.c` generating `SCPI_ERROR_INVALID_STRING_DATA` so closing this.
