### ISSUE TITLE
I can't find the function SCPI_ExprNumericListEntry() and SCPI_ExprChannelListEntry()

### ISSUE THREAD

**Issue by sergesarraillon** [j123b567/scpi-parser#79]
Just download the version 2.1... 
I checked in parser.h and I scan the directory libscpi.
I can't find these functions.

**Comment by j123b567** [comment]
You can try git head.

These functions are not released yet. I would like to finish issue #52 to release version 3.0 but I don't have a time to do so.

**Comment by sergesarraillon** [comment]
That's what I've done... and now it works...
Thanks
