### ISSUE TITLE
Implement standard OPERation status register callbacks

### ISSUE THREAD

**Issue by sandsbl** [j123b567/scpi-parser#82]
This issue is related to #81 to enhance status register support. I propose adding OPERation status register functionality in `minimal.c` by duplicating the existing functionality of `SCPI_StatusQuestionableEventQ`, `SCPI_StatusQuestionableEnableQ`, and `SCPI_StatusQuestionableEnable` callbacks.

**Comment by j123b567** [comment]
Same as #81, can you propose a pull request?
