### ISSUE TITLE
optional command part at start not supported

### ISSUE THREAD

**Issue by jancumps** [j123b567/scpi-parser#91]
Some instruments support optional command parts at the start of the command.
Example below is from [BK Precision 8600 series](https://bkpmedia.s3.amazonaws.com/downloads/programming_manuals/en-us/8600_Series_programming_manual.pdf):

`[SOURce:]CURRent[:LEVel][:IMMediate] <NRf+>`

The scpi lib supports the optional clauses LEVel and IMMediate.
I can't seem to make it work with the SOURce part at the start.
Error returned when I define the lib with the optional [SOURce:]
` -113,"Undefined header"`

**Comment by j123b567** [comment]
Try this pattern

    [:SOURce]:CURRent[:LEVel][:IMMediate]

**Comment by jancumps** [comment]
Perfect. That worked, Jan
Jan
